# Generated by Django 4.0.4 on 2022-06-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_author_musiclabel_alter_track_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='origin',
        ),
    ]
