# Generated by Django 4.0.4 on 2022-06-21 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_rename_first_name_author_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='musiclabel',
            name='label_date',
        ),
        migrations.AddField(
            model_name='musiclabel',
            name='label_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
