# Generated by Django 4.0.4 on 2022-06-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_rename_album_name_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musicapp.author'),
        ),
    ]
